### ISSUE TITLE
redundent warnings during compile

### ISSUE THREAD

**Issue by adlererik** [Nitrokey/nitrokey-pro-firmware#40]
Compiling master with 

$ gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516

Debian 9 Stable
Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

Will compile without error but there is a superfluous amount of warnings. Most of these warnings are very easy to fix. If I can find some time and there is interest I might do a code refactoring and clean up.

**Comment by szszszsz** [comment]
Hi @adlererik !
Thank you for the report. Indeed, looking at CI there is quite a number of warnings during the compilation. Since we are busy on some other topic at the moment, could you assist? Otherwise, some time should be available at the beginning of the next year for this task.
Regarding compiler: `gcc-arm-none-eabi` is used here, which last time I have checked stopped at 4.9. Could you paste its version?

**Comment by adlererik** [comment]
My arm tool chain looks like the following atm. I mostly use it for Gnuk coding but I also happen to own a NitroKey Pro and wanted to take a look at the code.

gcc-arm-none-eabi Version: 15:5.4.1+svn241155-1
gdb-arm-none-eabi Version: 7.12-6+9+b2
binutils-arm-none-eabi Version: 2.28-5+9+b3
libnewlib-arm-none-eabi Version: 2.4.0.20160527-2

Sure I can causally work on a code clean up. Like I said I own a NK Pro so I am doing everybody a favor. I’ll send it to you when I done or get bored with it.

**Comment by szszszsz** [comment]
Hi @adlererik !
By any chance, have you flashed the Pro with hand-compiled firmware using gcc 5.4.1? I tried it recently for fun, but device had not started and I have not investigated this further.
Release of v0.8 is compiled with gcc 4.9.
